version: '3.8'

services:
  server:
    container_name: project-1-server
    build: 
      context: ../../
      dockerfile: docker/dev/node.dockerfile
    volumes:
      - ../../src:/app/src
    ports:
      - 3000:3000
    depends_on: 
      - database
    networks: 
      - project-1-network
    command: sh -c './docker/dev/wait-for database:5432 -t 1000 -- npm run dev'
  database:
    container_name: project-1-db
    build:
      context: ../../
      dockerfile: docker/dev/db.dockerfile
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - project-1-network
    

volumes: 
  database-data: {}
networks:
  project-1-network: